[versions]
agp = "8.1.1"
kotlin = "2.0.21"
editor = "0.23.4-3895689-SNAPSHOT"
glide = "4.12.0"
koin = "4.0.0"

[libraries]

# AndroidX
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.8.2" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.0" }
androidx-desugar = { module = "com.android.tools:desugar_jdk_libs", version = "2.1.2" }
androidx-preference = { module = "androidx.preference:preference", version = "1.2.1" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version = "1.1.1" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.8.6" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version = "2.6.1" }

# Common
common-editor = { module = "io.github.Rosemoe.sora-editor:editor", version.ref = "editor" }
common-editor-textmate = { module = "io.github.Rosemoe.sora-editor:language-textmate", version.ref = "editor" }
common-prdownloader = { module = "com.github.amitshekhariitbhu:PRDownloader", version = "1.0.1" }

# UI
insetter = { module = "dev.chrisbanes.insetter:insetter", version = "0.6.1" }

# Google
google-guava = { module = "com.google.guava:guava", version = "33.0.0-jre" }
google-gson = { module = "com.google.code.gson:gson", version = "2.11.0" }
google-material = { module = "com.google.android.material:material", version = "1.12.0" }

# Glide
glide-glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }

# Koin
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin"}

# Kotlin
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.9.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
materialthemebuilder = { id = "dev.rikka.tools.materialthemebuilder", version = "1.4.1" }